version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      #- ${WEBAPP_STORAGE_HOME}/site:/data/db
      - ~/data:/data/db
    ports:
      - "27017:27017"

  web:
        build: .
        ports:
            - "8080:80"
            - "44348:443"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        depends_on:
            - mongo
        links:
          - mongo
